### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by sanny1** [LSPosed/LSPlt#3]
Hi,

Its sad to see you guys go, I believe most of the community was benefiting from your work, I definitely was, is there any guidance on how to use LSPlt. If you are still there ?

**Comment by yujincheng08** [comment]
https://lsposed.org/LSPlt/namespacelsplt.html

it should help.

**Comment by sanny1** [comment]
can I import it in a android app? :)

**Comment by yujincheng08** [comment]
yes

https://central.sonatype.com/artifact/org.lsposed.lsplt/lsplt

https://central.sonatype.com/artifact/org.lsposed.lsplt/lsplt-standalone

**Comment by sanny1** [comment]
whar would the build.gradle file look like for this, thank you so much for your help :)

**Comment by yujincheng08** [comment]
```
repositories {
    mavenCentral()
}

android {
    buildFeatures {
        prefab true
    }
}

dependencies {
    implementation "org.lsposed.lsplt:lsplt:1.2"
}
```
