### ISSUE TITLE
FindPltAddr returns false address

### ISSUE THREAD

**Issue by JingMatrix** [LSPosed/LSPlt#5]
For `libart.so` (Android 15), when we use `GnuLookup` to find the address of symbol `_ZN3art11ClassLinker22FixupStaticTrampolinesEPNS_6ThreadENS_6ObjPtrINS_6mirror5ClassEEE`, the method `Elf::FindPltAddr` return incorrect result.

To reproduce this issue with detailed logs, see https://github.com/JingMatrix/LSPosed/pull/5 .

The following implement of `GnuLookup` returns correct address:
https://github.com/JingMatrix/LSPosed/blob/086e3796eebd852e85d16a4bcd44f4ac57b655cf/core/src/main/jni/src/elf_util.cpp#L267-L290 .
However, in LSPlt, the method `GnuLookup` only returns the `idx` parameter, which is used to recover the actual address in the method `Elf::FindPltAddr`.
But this recovery step might contain mistakes, which cause the issue.

**Comment by yujincheng08** [comment]
Need libart.so

**Comment by JingMatrix** [comment]
Here is the [libart.so](https://drive.google.com/file/d/1itTQz5j-kDnMRXadiT7B6Hh6ube9b5I0/view?usp=sharing) uploaded to Google Drive.

**Comment by yujincheng08** [comment]
Confirmed LSPlt returns the correct address.

**Comment by JingMatrix** [comment]
> Confirmed LSPlt returns the correct address.

You are right, I mistook the function's address in memory as it PLT address.
